<template>
  <div id="app">
    <elTableAdminPage :columns="columns" :table-data="tableData" />
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      columns: [
        {
          label: "药品编码/流水号",
          prop: "medicineCode",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "药品类别",
          prop: "medicineType",
          feildType: "STRING",
          queryType: "EQ",
          isnull: false,
          form: true,
          query: true,
        },
        {
          label: "通用名",
          prop: "medicineName",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: false,
          form: true,
          query: true,
        },
        {
          label: "剂型",
          prop: "form",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "材质",
          prop: "material",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "规格",
          prop: "spec",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "包装单位",
          prop: "packUnit",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "生产企业",
          prop: "produceCompany",
          feildType: "STRING",
          queryType: "LIKE",
          isnull: true,
          form: true,
          query: true,
        },
        {
          label: "价格",
          prop: "retailPrice",
          feildType: "STRING",
          queryType: "EQ",
          isnull: false,
          form: true,
          query: true,
        },
        {
          label: "最小包装",
          prop: "minPackUnit",
          feildType: "STRING",
          isnull: true,
          form: true,
          query: false,
        },
        {
          label: "最小包装数值",
          prop: "minPackUnitInt",
          feildType: "STRING",
          isnull: true,
          form: true,
          query: false,
        },
        {
          label: "分类",
          prop: "type",
          feildType: "STRING",
          queryType: "EQ",
          isnull: false,
          form: true,
          query: true,
        },
        {
          label: "采购类别",
          prop: "orderType",
          feildType: "STRING",
          isnull: true,
          form: true,
          query: false,
        },
        {
          label: "更新时间",
          prop: "modifyTm",
          isnull: false,
          form: false,
          query: false,
        },
      ],
      tableData: [
        {
          id: "0048f1a9-81d0-4d0f-b5de-91623bd024d4",
          createTm: "2020-10-09T07:20:19.343+0000",
          modifyTm: "2020-10-09T07:20:19.343+0000",
          creatorId: "adminlgr",
          medicineType: "耗材",
          medicineName: "一次性使用医用口罩",
          form: "11",
          material: "11",
          spec: "175*95 mm平面挂耳式",
          packUnit: "只",
          produceCompany: "河南圣玛斯科技有限公司",
          retailPrice: 0.45,
          retailPriceInt: 45,
          minPackUnit: "10只/包",
          minPackUnitInt: 10,
          type: "耗材",
          orderType: "11",
        },
        {
          id: "a684a1b0-691e-4bb8-a564-e3d2ec46384b",
          createTm: "2020-10-09T07:20:19.343+0000",
          modifyTm: "2020-10-09T07:20:19.343+0000",
          creatorId: "adminlgr",
          medicineType: "耗材",
          medicineName: "医用外科口罩",
          spec: "175*95 mm系带式",
          packUnit: "只",
          produceCompany: "河南圣玛斯科技有限公司",
          retailPrice: 0.7,
          retailPriceInt: 70,
          minPackUnit: "1只/包",
          minPackUnitInt: 1,
          type: "耗材",
        },
        {
          id: "f27ebfb1-080c-428f-967e-acfbfcf16603",
          createTm: "2020-10-09T07:20:19.343+0000",
          modifyTm: "2020-10-09T07:20:19.343+0000",
          creatorId: "adminlgr",
          medicineType: "耗材",
          medicineName: "医用外科口罩",
          spec: "175*95 mm平面挂耳式",
          packUnit: "只",
          produceCompany: "河南圣玛斯科技有限公司",
          retailPrice: 0.6,
          retailPriceInt: 60,
          minPackUnit: "10只/包",
          minPackUnitInt: 10,
          type: "耗材",
        },
        {
          id: "14468b2a-6aa2-4087-b1b3-ad5c5b8e7ec0",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123243",
          medicineType: "耗材",
          medicineName: "卷式夹板",
          spec: "铝合金",
          packUnit: "卷",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 32,
          retailPriceInt: 3200,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "2443e522-028f-4b02-9564-294c93fd09b0",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123238",
          medicineType: "耗材",
          medicineName: "原棉",
          spec: "压缩500g",
          packUnit: "包",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 19.8,
          retailPriceInt: 1980,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "3767693d-ce51-444e-b2fe-b1bdf45a2e9f",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123239",
          medicineType: "耗材",
          medicineName: "原棉",
          spec: "压缩250g",
          packUnit: "包",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 10.2,
          retailPriceInt: 1020,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "50297078-f3d9-4903-bec3-c07e1ef32053",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123244",
          medicineType: "耗材",
          medicineName: "卡式止血带",
          spec: "卡式",
          packUnit: "条",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 22,
          retailPriceInt: 2200,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "5dcce965-e580-47a5-a993-9c89932e2a3e",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123241",
          medicineType: "耗材",
          medicineName: "三角巾",
          spec: "压缩",
          packUnit: "包",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 2.6,
          retailPriceInt: 260,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "6b36310b-8a5c-46ff-97e4-abb1983aee15",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123240",
          medicineType: "耗材",
          medicineName: "脱脂纱布",
          spec: "压缩0.75*10m",
          packUnit: "包",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 33,
          retailPriceInt: 3300,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
        {
          id: "9b5694ee-7ad3-416d-bc32-47b7eb89fe2e",
          createTm: "2020-10-09T07:20:07.119+0000",
          modifyTm: "2020-10-09T07:20:07.119+0000",
          creatorId: "adminlgr",
          medicineCode: "2123242",
          medicineType: "耗材",
          medicineName: "空勤急救包",
          spec: "无药",
          packUnit: "包",
          produceCompany: "际华三五四三针织服饰有限公司",
          retailPrice: 5.5,
          retailPriceInt: 550,
          minPackUnitInt: 1,
          type: "卫生敷料",
        },
      ],
    };
  },
};
</script>
